public class Principal {
    /**
     * 
     *  Declaração de atributos
     */

/** Metodo:Main (principal)
 * 
 */
 public static void main (String[]args)
 {
     
     //Carrega na memoria o objeto da classe Util.
     Util util=new Util();
     
     //Executa o metodo solicitado.
     util.digitarTexto();
     
     //Executa o método solicitado.
     util.exibirTexto();
 }        
}